apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: watcherconfigs.jabbs19.com
spec:
  group: jabbs19.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deployNamespace:
                  type: string
                watchNamespace:
                  type: string
                k8sApiVersion:
                  type: string
                k8sApiResourceName:
                  type: string
                annotationFilterBoolean:
                  type: string
                annotationFilterString:
                  type: string  
                status:
                  type: string  
                eventTypeFilter:
                  type: array
                  items:
                    type: string
                
  scope: Cluster
  names:
    plural: watcherconfigs
    singular: watcherconfig
    kind: WatcherConfig
    shortNames:
    - wc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watcherconfig-crd
rules:
- apiGroups:
  - jabbs19.com
  resources:
  - watcherconfig
  - watcherconfig/finalizers
  verbs: [ get, list, create, update, delete, deletecollection, watch ]